FROM node:18-alpine
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install
ARG PORT=80
ENV PORT=${PORT}
COPY . .
EXPOSE ${PORT}

CMD ["npm", "start", "--", "--host", "0.0.0.0", "--port", "${PORT}"]
